### ISSUE TITLE
Parse meta data of post

### ISSUE THREAD

**Issue by weakish** [weakish/plugins#8]
Parse meta data of post, e.g. title, category, tags.

**Comment by weakish** [comment]
Jekyll has this prefedined global variables:
- [ ] layout: I don't want to mess up with template system now.
- [ ] permalink: Just use file basename
- [ ] published: If you do not want to publish it yet, keep it in your local repository. Or put it into another directory, i.e. `drafts`.
- [x] category: Support space-separated string or YAML list We intend to only support one category.
- [x] tags. Support space-separated string or YAML list. We intend to only support space-separated strings.
- [x] title: Use it as blog title.

**Comment by weakish** [comment]
Done.
